### PR TITLE
fixes #32 Added onlinej.png

### LINKED ISSUE #32: Add image for OnlineJ

### PR DESCRIPTION
**Pull request by arnav-amb**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@arnav-amb awsm!!

**Comment by arnav-amb** [comment]
👍

**Comment by Compro-Prasad** [comment]
@arnav-amb It is a nice contribution but I suspect why it isn't an svg which would be much smaller in size and would fit in higher dimensions to get a good quality image. Better make PR for fixing this.

**Comment by ghoshbishakh** [comment]
@Compro-Prasad Unnecessary. A thumb is a thumb.

**Pull request merged**
